import { memo } from "preact/compat";
import { useEffect, useMemo, useState } from "preact/hooks";

type Katex = typeof import("katex").default;

/** KaTeX is loaded on the first formula, in its own chunk, so documents without math skip it. */
let katex: Katex | undefined;
let loading: Promise<Katex> | undefined;
const loadKatex = () => (loading ??= import("katex").then((m) => (katex = m.default)));

interface Props {
  value: string;
  display: boolean;
}

const escapeHtml = (text: string) =>
  text.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);

/**
 * KaTeX output. `trust: false` keeps `\href`/`\htmlClass` and friends disabled, so the markup is
 * generated by KaTeX alone and safe to inject. Memoized on the TeX source. Until KaTeX has
 * loaded, the TeX source is shown as plain text in the same element.
 */
export const MathView = memo(function MathView({ value, display }: Props) {
  const [ready, setReady] = useState(!!katex);
  useEffect(() => {
    if (!ready) void loadKatex().then(() => setReady(true));
  }, [ready]);
  const html = useMemo(
    () =>
      katex
        ? katex.renderToString(value, { displayMode: display, throwOnError: false, trust: false })
        : escapeHtml(value),
    [value, display, ready],
  );
  return display ? (
    <div class="zen-math" dangerouslySetInnerHTML={{ __html: html }} />
  ) : (
    <span class="zen-math-inline" dangerouslySetInnerHTML={{ __html: html }} />
  );
});
