import katex from "katex";
import { memo } from "preact/compat";
import { useMemo } from "preact/hooks";

interface Props {
  value: string;
  display: boolean;
}

/**
 * KaTeX output. `trust: false` keeps `\href`/`\htmlClass` and friends disabled, so the markup is
 * generated by KaTeX alone and safe to inject. Memoized on the TeX source.
 */
export const MathView = memo(function MathView({ value, display }: Props) {
  const html = useMemo(
    () => katex.renderToString(value, { displayMode: display, throwOnError: false, trust: false }),
    [value, display],
  );
  return display ? (
    <div class="zen-math" dangerouslySetInnerHTML={{ __html: html }} />
  ) : (
    <span class="zen-math-inline" dangerouslySetInnerHTML={{ __html: html }} />
  );
});
